-- SQL autogenerado desde archivos HTML de Ultrapelis
-- Fecha de generacion: 2026-03-03

PRAGMA foreign_keys = ON;

BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS categorias (
  id INTEGER PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS peliculas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  categoria_id INTEGER NOT NULL,
  titulo TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  ruta_html TEXT NOT NULL UNIQUE,
  descripcion TEXT,
  sinopsis TEXT,
  director TEXT,
  reparto TEXT,
  estreno_texto TEXT,
  duracion TEXT,
  idioma TEXT,
  calificacion TEXT,
  poster_url TEXT,
  embed_url TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (categoria_id) REFERENCES categorias(id)
);

DELETE FROM peliculas;
DELETE FROM categorias;

INSERT INTO categorias (id, nombre, slug) VALUES (1, 'Accion', 'accion');
INSERT INTO categorias (id, nombre, slug) VALUES (2, 'Animacion', 'animacion');
INSERT INTO categorias (id, nombre, slug) VALUES (3, 'Biografica', 'biografica');
INSERT INTO categorias (id, nombre, slug) VALUES (4, 'Ciencia Ficcion', 'ciencia-ficcion');
INSERT INTO categorias (id, nombre, slug) VALUES (5, 'Comedia', 'comedia');
INSERT INTO categorias (id, nombre, slug) VALUES (6, 'Deportes', 'deportes');
INSERT INTO categorias (id, nombre, slug) VALUES (7, 'Drama', 'drama');
INSERT INTO categorias (id, nombre, slug) VALUES (8, 'Fantasia', 'fantasia');
INSERT INTO categorias (id, nombre, slug) VALUES (9, 'Musical', 'musical');
INSERT INTO categorias (id, nombre, slug) VALUES (10, 'Superheroes', 'superheroes');
INSERT INTO categorias (id, nombre, slug) VALUES (11, 'Terror', 'terror');
INSERT INTO categorias (id, nombre, slug) VALUES (12, 'Thriller', 'thriller');

INSERT INTO peliculas (
  categoria_id, titulo, slug, ruta_html, descripcion, sinopsis, director, reparto, estreno_texto, duracion, idioma, calificacion, poster_url, embed_url
) VALUES
  (1, 'Deadpool y Wolverine', 'deadpool-wolverine', 'peliculas/accion/deadpool-wolverine.html', 'Mira Deadpool y Wolverine en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Deadpool altera su destino cuando la TVA lo recluta para una mision que amenaza multiples realidades. Para cumplirla, necesitara trabajar con un Wolverine marcado por la perdida, desatando una aventura violenta y caotica.', 'Shawn Levy', 'Ryan Reynolds, Hugh Jackman, Emma Corrin, Morena Baccarin, Rob Delaney, Leslie Uggams, Aaron Stanford, Matthew Macfadyen', '26 de julio de 2024', '2h 08m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/m2DeiTry0m2xS5p1V0B2l2MdaW.jpg', 'https://vimeos.net/embed-tmbjqufb955w.html'),
  (1, 'Gladiador II', 'gladiator-ii', 'peliculas/accion/gladiator-ii.html', 'Mira Gladiador II en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Anos despues de la muerte de Maximus, Lucius regresa a Roma y es arrastrado al coliseo en medio de una lucha por el poder imperial. Entre venganza y honor, tendra que decidir que tipo de lider quiere ser.', 'Ridley Scott', 'Paul Mescal, Pedro Pascal, Joseph Quinn, Fred Hechinger, Connie Nielsen, Denzel Washington', '22 de noviembre de 2024', '2h 28m', 'Español (Latino)', 'N/D', 'https://static.wikia.nocookie.net/doblaje/images/e/e0/GladiadorII-Poster.jpg/revision/latest?cb=20240923143904&path-prefix=es', 'https://vimeos.net/embed-k32v2qz0q9ug.html'),
  (1, 'Godzilla y Kong: El nuevo imperio', 'godzilla-x-kong-the-new-empire', 'peliculas/accion/godzilla-x-kong-the-new-empire.html', 'Mira Godzilla y Kong: El nuevo imperio en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Godzilla y Kong deben dejar de lado su rivalidad cuando una amenaza titanica emerge desde las profundidades de la Tierra Hueca. Junto a sus aliados humanos, enfrentaran una guerra que pondra en riesgo el equilibrio del planeta.', 'Adam Wingard', 'Rebecca Hall, Brian Tyree Henry, Dan Stevens, Kaylee Hottle, Alex Ferns, Fala Chen', '29 de marzo de 2024', '1h 55m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/z1p34vh7dE2xtafukL1Pi21eUOE.jpg', 'https://vimeos.net/embed-o58kx7htpsoj.html'),
  (1, 'John Wick: Capítulo 4', 'john-wick-chapter-4', 'peliculas/accion/john-wick-chapter-4.html', 'Mira John Wick: Capítulo 4 en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'John Wick busca vengarse del High Table y abrirse camino hacia su libertad enfrentando a nuevos enemigos y alianzas.', 'Chad Stahelski', 'Keanu Reeves, Donnie Yen, Bill Skarsgard, Laurence Fishburne, Hiroyuki Sanada, Shamier Anderson, Lance Reddick, Rina Sawayama, Scott Adkins, Clancy Brown, Ian McShane', '24 de marzo de 2023 (EE. UU.)', '2h 49m', 'Español (Latino)', 'R', 'https://www.themoviedb.org/t/p/original/0bdaPQHn0a62MLiJtVxw2tdu2O4.jpg', 'https://vimeos.net/embed-f4tp8s5fk17z.html'),
  (1, 'Sonic 3: La película', 'sonic-the-hedgehog-3', 'peliculas/accion/sonic-the-hedgehog-3.html', 'Mira Sonic 3: La película en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Sonic, Knuckles y Tails unen fuerzas para detener a Shadow, un rival con un poder que supera todo lo que han enfrentado. Para salvar el planeta, el equipo debera evolucionar y confiar incluso en aliados inesperados.', 'Jeff Fowler', 'Jim Carrey, Ben Schwartz, Krysten Ritter, Natasha Rothwell, Shemar Moore, James Marsden, Tika Sumpter, Idris Elba, Keanu Reeves', '20 de diciembre de 2024', '1h 50m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/zszRk5b8QPJ12IClS2PaWeA2Ibb.jpg', 'https://vimeos.net/embed-5z0kyms1zyct.html'),
  (2, 'Mi villano favorito 4', 'despicable-me-4', 'peliculas/animacion/despicable-me-4.html', 'Mira Mi villano favorito 4 en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Gru intenta adaptarse a su nueva vida familiar cuando una amenaza del pasado regresa para cobrar venganza. Con la ayuda de Lucy, las niñas y los Minions, debera proteger a los suyos en una aventura llena de caos.', 'Por definir', 'Por definir', 'Por definir', '1h 34m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/pW2T7B92KAnaiS2M223fI9QjILs.jpg', 'https://vimeos.net/embed-nhnyzqp2cznp.html'),
  (2, 'Intensa-Mente 2', 'inside-out-2', 'peliculas/animacion/inside-out-2.html', 'Mira Intensa-Mente 2 en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Riley entra en la adolescencia y su mente se transforma con la llegada de nuevas emociones lideradas por Ansiedad. Alegria y el resto del equipo tendran que encontrar un nuevo equilibrio para acompañarla en esta etapa.', 'Por definir', 'Por definir', 'Por definir', '1h 36m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/6u3sby4yvIYiL3pT62Ig22aTf4j.jpg', 'https://vimeos.net/embed-ygqbs42hctbc.html'),
  (2, 'Kung Fu Panda 4', 'kung-fu-panda-4', 'peliculas/animacion/kung-fu-panda-4.html', 'Mira Kung Fu Panda 4 en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Po recibe la tarea de convertirse en lider espiritual del Valle de la Paz, pero antes debe enfrentar a La Camaleona, una villana capaz de imitar a antiguos maestros. Para lograrlo, formara equipo con una astuta ladrona llamada Zhen.', 'Por definir', 'Por definir', 'Por definir', '1h 34m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/v9nGSRxI20e1d2ic3m9w2i5iE0.jpg', 'https://vimeos.net/embed-psdvmd18aq2a.html'),
  (2, 'Moana 2', 'moana-2', 'peliculas/animacion/moana-2.html', 'Mira Moana 2 en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Tras recibir un llamado de sus ancestros navegantes, Moana emprende un nuevo viaje hacia mares desconocidos para unir pueblos separados por generaciones. Con una tripulacion inesperada, enfrentara criaturas y tormentas legendarias.', 'Por definir', 'Por definir', 'Por definir', 'N/D', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/6o2Z2ui3T5y3o02Lpzs1Gv2vI3A.jpg', 'https://vimeos.net/embed-b7o6j67cn5pr.html'),
  (2, 'Ne Zha 2', 'ne-zha-2', 'peliculas/animacion/ne-zha-2.html', 'Mira Ne Zha 2 en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Despues de un gran sacrificio, Ne Zha y Ao Bing luchan por recuperar su forma y proteger a su gente de una nueva amenaza divina. Entre destino y amistad, ambos deberan dominar un poder capaz de cambiar su mundo.', 'Por definir', 'Por definir', 'Por definir', '2h 24m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/pghs2j2A1k1D222mX1vOFoP5yA.jpg', 'https://vimeos.net/embed-5op98hottk57.html'),
  (2, 'Spider-Man: A través del Spider-Verso', 'spider-man-across-the-spider-verse', 'peliculas/animacion/spider-man-across-the-spider-verse.html', 'Mira Spider-Man: A través del Spider-Verso en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Miles Morales viaja por el multiverso y descubre una red de Spider-Heroes que protege la continuidad de todos los mundos. Cuando una regla amenaza a su familia, debera desafiar el sistema y definir su propio camino.', 'Por definir', 'Por definir', 'Por definir', '2h 20m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/3753aRmu026aVI9sI1uSy2E22sF.jpg', 'https://vimeos.net/embed-fug6bx9d89st.html'),
  (2, 'Zootopia 2', 'zootopia-2', 'peliculas/animacion/zootopia-2.html', 'Mira Zootopia 2 en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Judy Hopps y Nick Wilde investigan un caso que sacude la convivencia en Zootopia y amenaza con dividir a sus habitantes. En una ciudad llena de nuevas especies y pistas falsas, su alianza sera clave para descubrir la verdad.', 'Por definir', 'Por definir', 'Por definir', '1h 48m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/q32q0J9OaIqjIqjAl13qaIaxQRy.jpg', 'https://vimeos.net/embed-80qf4rbpdhhr.html'),
  (3, 'Hamnet', 'hamnet', 'peliculas/biografica/hamnet.html', 'Mira Hamnet en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'En la Inglaterra isabelina, Agnes y William Shakespeare enfrentan la perdida de su hijo Hamnet, una herida que transforma para siempre a su familia. Entre duelo y memoria, el dolor se convierte en el impulso creativo de una obra inmortal.', 'Chloe Zhao', 'Jessie Buckley, Paul Mescal, Emily Watson, Joe Alwyn, Noah Jupe', '26 de noviembre de 2025', '2h 06m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/AmY0lHCoYp7g03i9yv0SBFvRyh.jpg', 'https://vimeos.net/embed-w5hu191cyki7.html'),
  (3, 'La máquina demoledora', 'the-smashing-machine', 'peliculas/biografica/the-smashing-machine.html', 'Mira La máquina demoledora en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Basada en la vida del peleador Mark Kerr, la historia muestra su ascenso en las artes marciales mixtas y el costo fisico y emocional de vivir al limite. Entre adiccion, fama y redencion, debera pelear la batalla mas dificil fuera del ring.', 'Benny Safdie', 'Dwayne Johnson, Emily Blunt, Ryan Bader, Bas Rutten, Oleksandr Usyk', '2025', '2h 03m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/The_Smashing_Machine_%282025_film%29.jpg/250px-The_Smashing_Machine_%282025_film%29.jpg', 'https://vimeos.net/embed-ttcu8c1pdo6q.html'),
  (4, 'Avatar', 'avatar-2009', 'peliculas/ciencia-ficcion/avatar-2009.html', 'Mira Avatar en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'En Pandora, un ex-marine se infiltra entre los Na vi y termina dividido entre su mision y la proteccion del planeta.', 'James Cameron', 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Michelle Rodriguez, Giovanni Ribisi', '18 de diciembre de 2009', '2h 42m', 'Español (Latino)', 'PG-13', 'https://www.themoviedb.org/t/p/original/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg', 'https://vimeos.net/embed-e713k3vlzuoq.html'),
  (4, 'Avatar: El camino del agua', 'avatar-the-way-of-water', 'peliculas/ciencia-ficcion/avatar-the-way-of-water.html', 'Mira Avatar: El camino del agua en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Jake y Neytiri forman una familia, pero una amenaza los obliga a buscar refugio entre los Metkayina.', 'James Cameron', 'Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Kate Winslet, Cliff Curtis', '16 de diciembre de 2022', '3h 12m', 'Español (Latino)', 'PG-13', 'https://www.themoviedb.org/t/p/original/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg', 'https://vimeos.net/embed-gbltuf2oorbv.html'),
  (4, 'Duna: Parte dos', 'dune-part-two', 'peliculas/ciencia-ficcion/dune-part-two.html', 'Mira Duna: Parte dos en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Paul Atreides se une a los Fremen en Arrakis y emprende una guerra de venganza contra los responsables de la caída de su familia, mientras enfrenta una decisión que podría cambiar el futuro del universo.', 'Denis Villeneuve', 'Timothée Chalamet, Zendaya, Rebecca Ferguson, Josh Brolin, Austin Butler, Florence Pugh, Dave Bautista, Christopher Walken', '1 de marzo de 2024 (EE. UU.)', '2h 46m', 'Español (Latino)', 'PG-13', 'https://www.themoviedb.org/t/p/original/8b8R8l88Qje9dn9OE8PY05ESeaB.jpg', 'https://vimeos.net/embed-kuyys5orh2c6.html'),
  (4, 'Jurassic World: Renace', 'jurassic-world-rebirth', 'peliculas/ciencia-ficcion/jurassic-world-rebirth.html', 'Mira Jurassic World: Renace en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'En una isla laboratorio de InGen con dinosaurios mutados, una fuga desencadena el caos y obliga a sobrevivir a amenazas nunca vistas.', 'Gareth Edwards', 'Scarlett Johansson, Mahershala Ali, Jonathan Bailey, Rupert Friend, Manuel Garcia-Rulfo, Ed Skrein', '2 de julio de 2025', '2h 13m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/b2p0Y22bZ2iLSX3G9s0I52jP05.jpg', 'https://vimeos.net/embed-r5xuubxljw1k.html'),
  (4, 'Lilo &amp; Stitch', 'lilo-stitch', 'peliculas/ciencia-ficcion/lilo-stitch.html', 'Mira Lilo &amp; Stitch en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Una nina hawaiana solitaria y un alienigena fugitivo forman un vinculo que ayuda a recomponer su familia.', 'Dean Fleischer Camp', 'Sydney Elizebeth Agudong, Billy Magnussen, Tia Carrere, Hannah Waddingham, Chris Sanders, Courtney B. Vance, Zach Galifianakis, Maia Kealoha', '23 de mayo de 2025', '1h 52m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/t6Hr3cCVQRb3pUeLd0e5aL4k3v.jpg', 'https://vimeos.net/embed-ph8dhp41s8sp.html'),
  (4, 'Depredador: Tierras salvajes', 'predator-badlands', 'peliculas/ciencia-ficcion/predator-badlands.html', 'Mira Depredador: Tierras salvajes en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'En un territorio hostil y sin ley, un grupo de sobrevivientes queda atrapado entre facciones humanas y un cazador extraterrestre perfecto. Cada decision puede ser la ultima en una caceria donde nadie esta a salvo.', 'Dan Trachtenberg', 'Elle Fanning, Dimitrius Schuster-Koloamatangi', '7 de noviembre de 2025', '1h 47m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Predator_Badlands_poster.jpg/500px-Predator_Badlands_poster.jpg', 'https://vimeos.net/embed-gifb0mvp14aw.html'),
  (4, 'El fugitivo', 'the-running-man', 'peliculas/ciencia-ficcion/the-running-man.html', 'Mira El fugitivo en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'En un futuro dominado por el entretenimiento violento, un hombre acusado injustamente es forzado a participar en un programa donde cazadores profesionales lo persiguen en vivo. Para sobrevivir, tendra que convertir el espectaculo en una rebelion.', 'Edgar Wright', 'Glen Powell, William H. Macy, Lee Pace, Michael Cera, Emilia Jones, Daniel Ezra, Jayme Lawson, Sean Hayes, Colman Domingo, Josh Brolin', '14 de noviembre de 2025', '2h 13m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/The_Running_Man_poster.jpg/500px-The_Running_Man_poster.jpg', 'https://vimeos.net/embed-qir4zwr4rqbi.html'),
  (4, 'Tron: Ares', 'tron-ares', 'peliculas/ciencia-ficcion/tron-ares.html', 'Mira Tron: Ares en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Ares, un programa de alta complejidad, cruza del mundo digital al mundo real y desata un conflicto sin precedentes entre humanos y tecnologia. Mientras las fronteras se rompen, una nueva carrera por el control de la realidad comienza.', 'Joachim Ronning', 'Jared Leto, Greta Lee, Evan Peters, Hasan Minhaj, Jodie Turner-Smith, Arturo Castro, Cameron Monaghan, Gillian Anderson, Jeff Bridges', '10 de octubre de 2025', '1h 59m', 'Español (Latino)', 'PG-13', 'https://www.themoviedb.org/t/p/original/z215E2S3m1b3jJp2iV32yqasC5Y.jpg', 'https://vimeos.net/embed-jph0jpxbe2kl.html'),
  (5, 'Barbie', 'barbie', 'peliculas/comedia/barbie.html', 'Mira Barbie en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Barbie y Ken viajan desde Barbieland al mundo real tras una crisis existencial y se enfrentan a nuevas realidades sobre si mismos.', 'Greta Gerwig', 'Margot Robbie, Ryan Gosling, America Ferrera, Kate McKinnon, Issa Rae, Rhea Perlman, Will Ferrell', '21 de julio de 2023 (EE. UU.)', '1h 54m', 'Español (Latino)', 'PG-13', 'https://www.themoviedb.org/t/p/original/fNtqD4BTFj0Bgo9lyoAtmNFzxHN.jpg', 'https://vimeos.net/embed-nvnyl2mw5s34.html'),
  (5, 'Bugonia', 'bugonia', 'peliculas/comedia/bugonia.html', 'Mira Bugonia en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Dos hombres convencidos de una conspiracion secuestran a una poderosa empresaria creyendo que es una amenaza para la humanidad. Lo que parece una mision absurda deriva en una satira feroz sobre poder, paranoia y control social.', 'Yorgos Lanthimos', 'Emma Stone, Jesse Plemons, Aidan Delbis, Stavros Halkias, Alicia Silverstone', '24 de octubre de 2025', '1h 58m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/bS62u25Gg32G5iPT3wB5gEa2u3A.jpg', 'https://vimeos.net/embed-omaxerxskfus.html'),
  (5, 'Una batalla tras otra', 'one-battle-after-another', 'peliculas/comedia/one-battle-after-another.html', 'Mira Una batalla tras otra en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Un exrevolucionario se ve obligado a volver a la accion cuando una figura de su pasado pone en peligro a su familia. En una huida llena de tension y humor negro, tendra que pelear una batalla tras otra para mantenerse con vida.', 'Paul Thomas Anderson', 'Leonardo DiCaprio, Sean Penn, Benicio del Toro, Regina Hall, Teyana Taylor, Chase Infiniti', '26 de septiembre de 2025', '2h 41m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/One_Battle_After_Another_poster.jpg/500px-One_Battle_After_Another_poster.jpg', 'https://vimeos.net/embed-205l01wtec4d.html'),
  (6, 'F1', 'f1', 'peliculas/deportes/f1.html', 'Mira F1 en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'El ex prodigio Sonny Hayes regresa a la Formula 1 para rescatar al equipo APXGP y demostrar que aun puede ganar.', 'Joseph Kosinski', 'Brad Pitt, Damson Idris, Kerry Condon, Tobias Menzies, Javier Bardem', '27 de junio de 2025', '2h 35m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/s5RTPB06M0i6w2aA4iA0oYdG32I.jpg', 'https://vimeos.net/embed-0f5b0dvl4iix.html'),
  (7, 'Downton Abbey: El gran final', 'downton-abbey-the-grand-finale', 'peliculas/drama/downton-abbey-the-grand-finale.html', 'Mira Downton Abbey: El gran final en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'La familia Crawley se enfrenta a cambios definitivos mientras Downton entra en una nueva era social y economica. Entre despedidas, reconciliaciones y decisiones de legado, cada personaje debera elegir su lugar en el futuro.', 'Simon Curtis', 'Hugh Bonneville, Jim Carter, Michelle Dockery, Paul Giamatti, Elizabeth McGovern, Penelope Wilton', '12 de septiembre de 2025', '2h 04m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5d/Downton_Abbey_The_Grand_Finale_poster.jpg/500px-Downton_Abbey_The_Grand_Finale_poster.jpg', 'https://vimeos.net/embed-5l4k62rehsmw.html'),
  (7, 'Oppenheimer', 'oppenheimer', 'peliculas/drama/oppenheimer.html', 'Mira Oppenheimer en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Sigue la vida de J. Robert Oppenheimer y su papel en el desarrollo de las primeras armas nucleares durante la Segunda Guerra Mundial.', 'Christopher Nolan', 'Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr., Florence Pugh', '21 de julio de 2023 (EE. UU.)', '3h 00m', 'Español (Latino)', 'R', 'https://www.themoviedb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg', 'https://vimeos.net/embed-klxgsdzm21sx.html'),
  (8, 'Una película de Minecraft', 'a-minecraft-movie', 'peliculas/fantasia/a-minecraft-movie.html', 'Mira Una película de Minecraft en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Steve descubre un portal al Overworld y termina enfrentando una amenaza del Nether mientras otros personajes se ven arrastrados a ese mundo cubico.', 'Jared Hess', 'Jason Momoa, Jack Black, Emma Myers, Danielle Brooks, Sebastian Hansen, Jennifer Coolidge', '4 de abril de 2025', '1h 41m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/qYg2G83s2iGQiIu0e1aCifn2y08.jpg', 'https://doodstream.com/e/98zukoh5jqiw'),
  (8, 'Cómo entrenar a tu dragón', 'how-to-train-your-dragon', 'peliculas/fantasia/how-to-train-your-dragon.html', 'Mira Cómo entrenar a tu dragón en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'En Berk, Hiccup derriba a un Night Fury pero decide salvarlo, iniciando una amistad que cambiara la guerra entre vikingos y dragones.', 'Dean DeBlois', 'Mason Thames, Nico Parker, Gabriel Howell, Julian Dennison, Bronwyn James, Harry Trevaldwyn, Peter Serafinowicz, Ruth Codd, Naomi Wirthner, Nick Frost, Gerard Butler', '13 de junio de 2025', '2h 05m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/pE8S52Tj9i23MubfIuNci2yKj5S.jpg', 'https://vimeos.net/embed-7z7tt94ll0ud.html'),
  (9, 'Wicked: Para siempre', 'wicked-for-good', 'peliculas/musical/wicked-for-good.html', 'Mira Wicked: Para siempre en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Elphaba y Glinda toman caminos opuestos mientras Oz entra en una etapa de conflicto politico y emocional. Su amistad sera puesta a prueba en una historia de decisiones definitivas, sacrificio y legado.', 'Jon M. Chu', 'Ariana Grande, Cynthia Erivo, Jonathan Bailey, Ethan Slater, Bowen Yang, Michelle Yeoh, Jeff Goldblum', '21 de noviembre de 2025', '2h 17m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/Wicked_For_Good_poster.jpg/1200px-Wicked_For_Good_poster.jpg', 'https://vimeos.net/embed-k651210a60eq.html'),
  (9, 'Wicked', 'wicked', 'peliculas/musical/wicked.html', 'Mira Wicked en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Antes de Dorothy, dos jovenes brujas forjan una amistad improbable en la Universidad Shiz. Entre prejuicios, poder y politica, su relacion cambiara para siempre el destino de Oz.', 'Jon M. Chu', 'Cynthia Erivo, Ariana Grande, Jonathan Bailey, Ethan Slater, Bowen Yang, Peter Dinklage, Michelle Yeoh, Jeff Goldblum, Marissa Bode', '22 de noviembre de 2024', '2h 40m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/pYR35j5sL4OnaA3aKjJp2hmXGgB.jpg', 'https://vimeos.net/embed-xknvzuxn6xxy.html'),
  (10, 'Superman', 'superman', 'peliculas/superheroes/superman.html', 'Mira Superman en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Superman enfrenta una amenaza metahumana y las intrigas de Lex Luthor mientras protege Metropolis.', 'James Gunn', 'David Corenswet, Rachel Brosnahan, Nicholas Hoult, Edi Gathegi, Anthony Carrigan, Nathan Fillion, Isabela Merced', '11 de julio de 2025', '2h 09m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/hO1m2GN2O0A3pIO9p0V3g8f5pY.jpg', 'https://vimeos.net/embed-ncph02w1zpi2.html'),
  (11, '28 años después', '28-years-later', 'peliculas/terror/28-years-later.html', 'Mira 28 años después en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Han pasado casi tres decadas desde el brote del virus de la rabia. En una Gran Bretana aislada y devastada, un nuevo grupo de sobrevivientes enfrenta mutaciones, violencia y decisiones extremas para mantenerse con vida.', 'Danny Boyle', 'Jodie Comer, Aaron Taylor-Johnson, Jack O''Connell, Alfie Williams, Ralph Fiennes', '20 de junio de 2025', '1h 55m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/38/28_Years_Later_film_poster.jpg/1200px-28_Years_Later_film_poster.jpg', 'https://vimeos.net/embed-pa7gebprea45.html'),
  (11, 'El teléfono negro 2', 'black-phone-2', 'peliculas/terror/black-phone-2.html', 'Mira El teléfono negro 2 en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Mientras intenta rehacer su vida, Finney vuelve a escuchar el telefono negro y descubre que una nueva ola de desapariciones esta conectada con el pasado de The Grabber. Junto con Gwen, debera enfrentar visiones cada vez mas oscuras para cortar el ciclo de violencia antes de que sea demasiado tarde.', 'Scott Derrickson', 'Mason Thames, Madeleine McGraw, Jeremy Davies, Demián Bichir, Ethan Hawke', '17 de octubre de 2025', '1h 54m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/3K22viV92A02TElo3aF1i4u42D.jpg', 'https://vimeos.net/embed-8ccjehly70qf.html'),
  (11, 'Buen chico', 'good-boy', 'peliculas/terror/good-boy.html', 'Mira Buen chico en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Una familia se muda a una casa aislada para empezar de nuevo, pero su perro detecta presencias que nadie mas quiere creer. Lo que comienza como una inquietud domestica se convierte en una lucha desesperada por sobrevivir a una amenaza sobrenatural.', 'Jan Komasa', 'Stephen Graham, Andrea Riseborough, Anson Boon, Kit Rakusen', '5 de septiembre de 2025', '1h 50m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Good_Boy_2025_film_poster.jpg/250px-Good_Boy_2025_film_poster.jpg', ''),
  (11, 'Él', 'him', 'peliculas/terror/him.html', 'Mira Él en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Un mariscal de campo universitario lesionado recibe la oportunidad de entrenar con una leyenda del deporte, pero pronto descubre un entorno obsesionado con el sacrificio extremo. Entre fama, dolor y manipulacion, debera decidir hasta donde esta dispuesto a llegar para triunfar.', 'Justin Tipping', 'Marlon Wayans, Tyriq Withers, Julia Fox, Tim Heidecker, Jim Jefferies', '19 de septiembre de 2025', '1h 36m', 'Español (Latino)', 'N/D', 'https://m.media-amazon.com/images/M/MV5BNjA5NzlmYjUtM2JlZS00M2M3LWIxYTYtY2Y2NzUxYjlhNGUwXkEyXkFqcGc@._V1_QL75_UX328_.jpg', 'https://vimeos.net/embed-6966te5k0od6.html'),
  (11, 'El Conjuro: Últimos ritos', 'the-conjuring-last-rites', 'peliculas/terror/the-conjuring-last-rites.html', 'Mira El Conjuro: Últimos ritos en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Ed y Lorraine Warren aceptan un ultimo caso cuando una familia afirma estar siendo acosada por una entidad que desafia todos sus registros anteriores. Para detenerla, tendran que arriesgar su fe y su vida en el enfrentamiento mas peligroso de su carrera.', 'Michael Chaves', 'Vera Farmiga, Patrick Wilson, Mia Tomlinson, Ben Hardy', '5 de septiembre de 2025', '2h 15m', 'Español (Latino)', 'N/D', 'https://www.themoviedb.org/t/p/original/uYmoADg1iT4sTQuh1a3pGz1kX2.jpg', 'https://vimeos.net/embed-pazypz5yf1vk.html'),
  (12, 'Después de la cacería', 'after-the-hunt', 'peliculas/thriller/after-the-hunt.html', 'Mira Después de la cacería en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Una respetada profesora universitaria queda atrapada entre una acusacion grave contra un colega y un secreto de su propio pasado. Cuando la verdad sale a la luz, su prestigio y su vida personal comienzan a derrumbarse.', 'Luca Guadagnino', 'Julia Roberts, Ayo Edebiri, Andrew Garfield, Michael Stuhlbarg, Chloë Sevigny', '10 de octubre de 2025', '2h 19m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/After_the_Hunt_poster.jpg/250px-After_the_Hunt_poster.jpg', 'https://www.2embed.online/embed/movie/tt32159989'),
  (12, 'La larga caminata', 'the-long-walk', 'peliculas/thriller/the-long-walk.html', 'Mira La larga caminata en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'En un regimen autoritario, cien jovenes participan en una competencia mortal donde detenerse significa morir. A medida que la caminata avanza, la amistad, la culpa y el instinto de supervivencia chocan en un viaje fisico y emocional sin retorno.', 'Francis Lawrence', 'Cooper Hoffman, David Jonsson, Garrett Wareing, Tut Nyuot, Charlie Plummer, Ben Wang, Roman Griffin Davis, Josh Hamilton, Judy Greer, Mark Hamill', '12 de septiembre de 2025', '1h 48m', 'Español (Latino)', 'N/D', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/The_Long_Walk_%282025_film%29.jpg/250px-The_Long_Walk_%282025_film%29.jpg', 'https://vimeos.net/embed-rw58x1x4hp1y.html'),
  (2, 'Spider-Man: Un nuevo universo', 'spider-man-into-the-spider-verse', 'peliculas/animacion/spider-man-into-the-spider-verse.html', 'Mira Spider-Man: Un nuevo universo (2018) en Ultrapelis. Consulta ficha tecnica, sinopsis y opciones para ver la pelicula en linea.', 'Miles Morales, un adolescente de Brooklyn, se convierte en el Hombre Araña de su realidad y cruza caminos con cinco contrapartes de otras dimensiones para detener una amenaza para todas las realidades.', 'Bob Persichetti, Peter Ramsey', 'Shameik Moore, Jake Johnson, Hailee Steinfeld, Mahershala Ali, Brian Tyree Henry', '14 de diciembre de 2018', '1h 57m', 'Español (Latino)', 'PG', 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg', '../../no-video.html'),

COMMIT;
